apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dzor17dwp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzor17dwp-go 
  name: dzor17dwp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dzor17dwp-go 
