apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dzor17dwp-go 
  janus-idp.io/tekton: dzor17dwp-go
  backstage.io/kubernetes-id: dzor17dwp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dzor17dwp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml